#!/usr/bin/env python3
"""Generate a provenance-labelled I--Love--Q reference visualization.

The maintained calculation supplies a runtime TOV/tidal sequence and therefore
the Lambda values.  This entry point applies the published Yagi--Yunes fits to
those values.  It does *not* solve a rotating star's moment of inertia or
quadrupole, so the figure is a transform-only visualization, not a test of
EOS universality.  A radius-based moment-of-inertia estimate is retained as a
descriptive overlay; its maximum deviation is reported explicitly and is not
used as an acceptance gate.

Output: ``verification/fig_iloveq_universal.png`` and the accompanying
``verification/fig_iloveq_universal_report.json``.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

# Physical constants used only for the descriptive radius-based I estimate.
G_cgs = 6.674e-8
c_cgs = 2.998e10
M_sun_g = 1.989e33
M_sun_km = 1.4766


# Yagi--Yunes published fit coefficients.  These are transforms of runtime
# Lambda values, not parameters fitted to the VMF sequence.
ILOVE_COEFFS = {
    "a": 1.496,
    "b": 0.05951,
    "c": 0.02238,
    "d": -6.953e-4,
    "e": 8.345e-6,
}
QLOVE_COEFFS = {
    "a": 0.1940,
    "b": 0.09163,
    "c": 0.04812,
    "d": -4.283e-4,
    "e": 1.245e-6,
}


def yy_fit(ln_x: np.ndarray | float, coeffs: dict[str, float]) -> np.ndarray | float:
    """Evaluate a Yagi--Yunes logarithmic polynomial transform."""

    a, b, c, d, e = (coeffs[key] for key in ("a", "b", "c", "d", "e"))
    return a + b * ln_x + c * ln_x**2 + d * ln_x**3 + e * ln_x**4


def _radius_i_estimate(mass: float, radius: float) -> float:
    """Return a descriptive radius-based I-bar estimate (not an I solve)."""

    compactness = mass * M_sun_km / radius
    factor = 0.237 * (1.0 + 2.84 * compactness + 18.9 * compactness**4)
    radius_cm = radius * 1.0e5
    i_cgs = factor * mass * M_sun_g * radius_cm**2
    return float(i_cgs * c_cgs**4 / (G_cgs**2 * (mass * M_sun_g) ** 3))


def compute_vmf_sequence() -> list[dict[str, Any]]:
    """Compute the stable runtime EOS sequence and transform-only I/Q rows."""

    import nvg_tidal_deformability as tidal

    eos = tidal.EOS()
    # Keep the canonical suite's pressure grid so Lambda_1.4 and the stable
    # branch are the same runtime values consumed by downstream reports.
    pressures = np.logspace(-1.0, 3.4, 120)
    raw: list[tuple[float, float, float, float]] = []
    for pressure in pressures:
        mass, radius, k2, tidal_lambda = tidal.solve_tov_tidal(eos, float(pressure))
        if mass > 0.8 and radius > 5.0 and k2 > 0.0 and tidal_lambda > 0.0:
            raw.append((float(mass), float(radius), float(k2), float(tidal_lambda)))
    if not raw:
        raise RuntimeError("canonical EOS produced no valid TOV/tidal sequence")

    max_index = int(np.argmax([row[0] for row in raw]))
    stable = sorted(raw[: max_index + 1], key=lambda row: row[0])
    masses = np.array([row[0] for row in stable])
    radii = np.array([row[1] for row in stable])
    k2s = np.array([row[2] for row in stable])
    lambdas = np.array([row[3] for row in stable])

    target_masses = [
        1.0,
        1.1,
        1.2,
        1.3,
        1.338,
        1.4,
        1.5,
        1.6,
        1.7,
        1.8,
        1.9,
        2.0,
        2.1,
    ]
    sequence: list[dict[str, Any]] = []
    for mass in target_masses:
        if mass < masses.min() or mass > masses.max():
            continue
        tidal_lambda = float(np.interp(mass, masses, lambdas))
        radius = float(np.interp(mass, masses, radii))
        k2 = float(np.interp(mass, masses, k2s))
        if tidal_lambda <= 1.0:
            continue

        i_transform = float(np.exp(yy_fit(np.log(tidal_lambda), ILOVE_COEFFS)))
        q_transform = float(np.exp(yy_fit(np.log(tidal_lambda), QLOVE_COEFFS)))
        i_radius = _radius_i_estimate(mass, radius)
        sequence.append(
            {
                "M": float(mass),
                "R": radius,
                "k2": k2,
                "Lambda": tidal_lambda,
                "I_bar_radius_estimate": i_radius,
                "I_bar_transform": i_transform,
                "Q_bar_transform": q_transform,
                "I_relative_deviation": abs(i_radius - i_transform) / i_transform,
                # Q is generated by the transform itself; this zero is not an
                # independent agreement measurement.
                "Q_relative_deviation": 0.0,
            }
        )
    if len(sequence) < 3:
        raise RuntimeError("canonical EOS sequence has fewer than three valid masses")
    return sequence


def summarize_sequence(sequence: list[dict[str, Any]]) -> dict[str, Any]:
    """Summarize deviations with maximum, not mean-square, semantics."""

    if not sequence:
        raise ValueError("cannot summarize an empty sequence")
    i_deviations = [row["I_relative_deviation"] for row in sequence]
    q_deviations = [row["Q_relative_deviation"] for row in sequence]
    max_i = float(max(i_deviations))
    max_q = float(max(q_deviations))
    return {
        "status": "TRANSFORM_ONLY_NO_INDEPENDENT_IQ_SOLVE",
        "source": "nvg_tidal_deformability.EOS + solve_tov_tidal; Yagi-Yunes transforms",
        "independent_i_solve": False,
        "independent_q_solve": False,
        "max_i_relative_deviation": max_i,
        "max_q_relative_deviation": max_q,
        "max_relative_deviation": max(max_i, max_q),
        "max_deviation": max(max_i, max_q),
        "deviation_metric": "max_absolute_relative_per_point",
        "max_deviation_semantics": (
            "maximum absolute per-point relative deviation; descriptive only; "
            "no tolerance or acceptance gate"
        ),
        "tolerance_gate": None,
        "sequence_count": len(sequence),
        "lambda_14": next(
            row["Lambda"] for row in sequence if abs(row["M"] - 1.4) < 1.0e-12
        ),
    }


def _report_payload(sequence: list[dict[str, Any]], summary: dict[str, Any]) -> dict[str, Any]:
    """Return the JSON-serializable provenance and computed rows."""

    import nvg_tidal_deformability as tidal

    return {
        "source_script": "verification/nvg_iloveq_plot.py",
        "figure": "verification/fig_iloveq_universal.png",
        "status": summary["status"],
        "source": summary["source"],
        "canonical_selection": tidal.CANONICAL_SELECTION,
        "summary": summary,
        "sequence": sequence,
    }


def main() -> dict[str, Any]:
    sequence = compute_vmf_sequence()
    summary = summarize_sequence(sequence)
    payload = _report_payload(sequence, summary)

    print("=" * 80)
    print("     NVG I-LOVE-Q REFERENCE VISUALIZATION (TRANSFORM ONLY)")
    print("=" * 80)
    print(
        f"Runtime TOV/tidal rows: {summary['sequence_count']}; "
        f"Lambda_1.4 = {summary['lambda_14']:.3f}"
    )
    print(f"Status: {summary['status']}")
    print(
        "Maximum descriptive |I_radius - I_transform|/I_transform = "
        f"{summary['max_i_relative_deviation'] * 100.0:.3f}%"
    )
    print("Q values are Yagi-Yunes transforms of the same runtime Lambda values.")
    print("No independent I/Q solve, universality claim, or tolerance gate is made.")

    lambda_range = np.logspace(0.5, 4.5, 200)
    i_curve = np.exp(yy_fit(np.log(lambda_range), ILOVE_COEFFS))
    q_curve = np.exp(yy_fit(np.log(lambda_range), QLOVE_COEFFS))
    vmf_lambda = np.array([row["Lambda"] for row in sequence])
    vmf_i_radius = np.array([row["I_bar_radius_estimate"] for row in sequence])
    vmf_i_transform = np.array([row["I_bar_transform"] for row in sequence])
    vmf_q_transform = np.array([row["Q_bar_transform"] for row in sequence])
    vmf_masses = np.array([row["M"] for row in sequence])

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 12,
            "axes.linewidth": 1.2,
            "xtick.major.width": 1.0,
            "ytick.major.width": 1.0,
            "xtick.direction": "in",
            "ytick.direction": "in",
            "xtick.top": True,
            "ytick.right": True,
        }
    )
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.5))
    for axis in (ax1, ax2):
        axis.set_facecolor("#fafafa")

    ax1.plot(
        lambda_range,
        i_curve,
        color="#888888",
        linewidth=2.0,
        label="Yagi-Yunes fit (reference transform)",
    )
    scatter1 = ax1.scatter(
        vmf_lambda,
        vmf_i_radius,
        c=vmf_masses,
        cmap="coolwarm",
        s=75,
        zorder=5,
        edgecolors="#333333",
        linewidths=0.8,
        vmin=1.0,
        vmax=2.2,
        label="radius-based I estimate (descriptive)",
    )
    ax1.scatter(
        vmf_lambda,
        vmf_i_transform,
        facecolors="none",
        edgecolors="#222222",
        s=34,
        zorder=6,
        label="I transform of runtime Lambda",
    )

    idx_14 = int(np.argmin(np.abs(vmf_masses - 1.4)))
    ax1.plot(vmf_lambda[idx_14], vmf_i_radius[idx_14], "D", color="#ff6b6b", markersize=11, markeredgecolor="black", zorder=7)
    ax1.annotate(
        rf"$\Lambda_{{1.4}} = {vmf_lambda[idx_14]:.0f}$",
        xy=(vmf_lambda[idx_14], vmf_i_radius[idx_14]),
        xytext=(vmf_lambda[idx_14] * 2.4, vmf_i_radius[idx_14] * 1.15),
        fontsize=10,
        color="#c0392b",
        arrowprops={"arrowstyle": "->", "color": "#c0392b", "lw": 1.2},
    )
    ax1.set_xscale("log")
    ax1.set_yscale("log")
    ax1.set_xlabel(r"Tidal deformability $\Lambda$", fontsize=13)
    ax1.set_ylabel(r"Dimensionless moment of inertia $\bar{I}$", fontsize=13)
    ax1.set_title(r"I–Love (descriptive transform)", fontsize=13, fontweight="bold", pad=10)
    ax1.legend(loc="upper left", fontsize=8, framealpha=0.9, edgecolor="#cccccc")
    ax1.grid(True, which="both", linestyle="--", alpha=0.15)
    ax1.set_xlim(1, 3e4)
    ax1.set_ylim(3, 50)

    ax2.plot(
        lambda_range,
        q_curve,
        color="#888888",
        linewidth=2.0,
        label="Yagi-Yunes fit (reference transform)",
    )
    scatter2 = ax2.scatter(
        vmf_lambda,
        vmf_q_transform,
        c=vmf_masses,
        cmap="coolwarm",
        s=75,
        zorder=5,
        edgecolors="#333333",
        linewidths=0.8,
        vmin=1.0,
        vmax=2.2,
        label="Q transform of runtime Lambda",
    )
    ax2.plot(vmf_lambda[idx_14], vmf_q_transform[idx_14], "D", color="#ff6b6b", markersize=11, markeredgecolor="black", zorder=7)
    ax2.annotate(
        rf"$\Lambda_{{1.4}} = {vmf_lambda[idx_14]:.0f}$",
        xy=(vmf_lambda[idx_14], vmf_q_transform[idx_14]),
        xytext=(vmf_lambda[idx_14] * 2.4, vmf_q_transform[idx_14] * 1.15),
        fontsize=10,
        color="#c0392b",
        arrowprops={"arrowstyle": "->", "color": "#c0392b", "lw": 1.2},
    )
    ax2.set_xscale("log")
    ax2.set_yscale("log")
    ax2.set_xlabel(r"Tidal deformability $\Lambda$", fontsize=13)
    ax2.set_ylabel(r"Dimensionless quadrupole moment $\bar{Q}$", fontsize=13)
    ax2.set_title(r"Q–Love (transform only)", fontsize=13, fontweight="bold", pad=10)
    ax2.legend(loc="upper left", fontsize=8, framealpha=0.9, edgecolor="#cccccc")
    ax2.grid(True, which="both", linestyle="--", alpha=0.15)
    ax2.set_xlim(1, 3e4)
    ax2.set_ylim(1, 100)

    cbar = fig.colorbar(scatter1, ax=[ax1, ax2], shrink=0.85, pad=0.02)
    cbar.set_label(r"Stellar mass $M\;[M_\odot]$", fontsize=11)
    fig.text(
        0.5,
        0.01,
        "Transform-only; no independent I/Q solve. "
        + f"Max descriptive I deviation = {summary['max_i_relative_deviation'] * 100.0:.2f}%; no tolerance gate.",
        ha="center",
        fontsize=9,
        color="#555555",
        style="italic",
    )
    # Manual spacing avoids tight_layout's incompatibility warning with the
    # shared colorbar while leaving room for the provenance footer.
    fig.subplots_adjust(bottom=0.14, right=0.88, wspace=0.25)

    plot_path = os.path.join(_HERE, "fig_iloveq_universal.png")
    report_path = os.path.join(_HERE, "fig_iloveq_universal_report.json")
    plt.savefig(plot_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close()
    with open(report_path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")
    print(f"Saved: {plot_path}")
    print(f"Saved: {report_path}")
    return payload


if __name__ == "__main__":
    main()
