#!/usr/bin/env python3
"""Audit the verification table without manufacturing a global p-value.

The canonical NS transition was selected using the J0740, GW170817, and NICER
constraints.  Those observations are therefore in-sample for the maintained
NS chain.  This entry point computes descriptive runtime pulls when requested,
but explicitly withholds a global significance/p-value because no traceable
held-out producer is available.  A README status count is presentation
metadata only and never supplies numerical pulls.
"""

from __future__ import annotations

import os
import re
import sys
from typing import Any

if os.path.dirname(os.path.abspath(__file__)) not in sys.path:
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


README = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "README.md")

STATUS_BUCKETS = [
    ("✅", "compatible with data"),
    ("📏", "interval prediction"),
    ("🔭", "forward prediction (no data yet)"),
    ("⚙️", "calibration / consistency / conditional"),
    ("⚪", "null test / no predictive content"),
    ("📐", "mathematical result"),
    ("❓", "conjectural / speculative"),
    ("❌", "open problem / retired"),
    ("⏳", "awaiting experiment"),
    ("⚠️", "tension flagged"),
]

# Compatibility placeholders only.  Numerical pulls are generated by
# ``runtime_conditional_rows``; no literal result table is embedded here.
PULLS: tuple[object, ...] = ()
BLOCKS: tuple[object, ...] = ()


def readme_status_counts(path: str = README) -> tuple[int, dict[str, int]]:
    """Count numbered status rows without treating the table as measurements."""

    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    counts: dict[str, int] = {}
    n_rows = 0
    for number, status in re.findall(r"^\| (\d+) \|.*\|(.*)\|\s*$", text, re.M):
        if not 1 <= int(number) <= 60:
            continue
        n_rows += 1
        for symbol, _label in STATUS_BUCKETS:
            if symbol in status:
                counts[symbol] = counts.get(symbol, 0) + 1
                break
    return n_rows, counts


def runtime_conditional_rows() -> list[dict[str, Any]]:
    """Build pulls from the canonical solver and declared observations only."""

    import nvg_joint_ns_inference as joint

    predictions, metadata = joint.compute_nvg_predictions()
    result = joint.run_joint_inference(predictions, metadata)
    rows = []
    for row in result["rows"]:
        if row["included"]:
            rows.append(
                {
                    "key": row["key"],
                    "prediction": row["prediction"],
                    "observation": row["observation"],
                    "sigma": row["sigma"],
                    "pull": row["pull"],
                    "kind": "conditional/in-sample",
                    "source": joint.OBSERVATIONS[row["key"]]["source"],
                    "selection_provenance": metadata["selection_provenance"],
                }
            )
    return rows


def main() -> dict[str, Any]:
    n_rows, counts = readme_status_counts()
    rows = runtime_conditional_rows()
    provenance = rows[0]["selection_provenance"] if rows else {
        "selected_by": "verification/nvg_ns_parameter_scan.py",
        "selection_method": "best_margin_survivor_on_explicit_grid",
    }
    chi2 = sum(float(row["pull"]) ** 2 for row in rows)
    print("=" * 78)
    print("  NVG VERIFICATION-TABLE STATISTICS AUDIT")
    print("=" * 78)
    print(f"Status taxonomy: {n_rows} numbered README rows (presentation metadata only)")
    for symbol, label in STATUS_BUCKETS:
        if counts.get(symbol):
            print(f"  {symbol} {counts[symbol]:>2} {label}")
    print()
    print("Runtime NS comparison rows (all conditional/in-sample):")
    print(f"Selection provenance: {provenance['selected_by']} / {provenance['selection_method']}")
    for row in rows:
        print(
            f"  {row['key']:<18} pred={row['prediction']:.3f} "
            f"obs={row['observation']:.3f} pull={row['pull']:+.3f} ({row['source']})"
        )
    print(f"Conditional/in-sample chi-squared = {chi2:.3f} over {len(rows)} rows")
    print("Global p-value: WITHHELD — no traceable held-out producer exists.")
    print("No independent/global significance or confirmation claim is made.")
    print("=" * 78)
    return {
        "status_rows": n_rows,
        "status_counts": counts,
        "rows": rows,
        "selection_provenance": provenance,
        "chi_squared": chi2,
        "p_value": None,
        "status": "WITHHELD_NO_HELD_OUT_PRODUCER",
    }


if __name__ == "__main__":
    main()
