"""Semantic checks for the Phase 4 runner/dashboard and EOS-bound repair."""

from __future__ import annotations

import contextlib
import io
import os
import sys
import unittest
from pathlib import Path

import numpy as np
from scipy.interpolate import interp1d


HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import nvg_direct_urca as direct_urca
import nvg_eos_beta_css_softening as css
import nvg_falsifier_dashboard as dashboard
import nvg_full_ns_eos as full_ns
import nvg_hyperon_puzzle_tov as hyperon
import nvg_magnetar_mass_correlation as magnetar
import run_all_checks


class RunnerDashboardBoundsTests(unittest.TestCase):
    def test_dashboard_is_structured_unassessed_metadata(self):
        rows = dashboard.evaluate_registry()
        self.assertTrue(rows)
        self.assertTrue(all(row["evidence_status"] == "UNASSESSED_NO_LIVE_PRODUCER" for row in rows))
        rendered = io.StringIO()
        with contextlib.redirect_stdout(rendered):
            self.assertEqual(dashboard.main(), 0)
        text = rendered.getvalue()
        self.assertIn("NO LIVE SCIENTIFIC VERDICT", text)
        self.assertNotIn("ALIVE", text)
        self.assertNotIn("8/8", text)

    def test_runner_does_not_render_static_claims(self):
        original = run_all_checks.CHECKS
        try:
            run_all_checks.CHECKS = [{"name": "probe", "script": "missing.py", "critical": False}]
            run_all_checks.OPTIONAL_CHECKS = []
            rendered = io.StringIO()
            with contextlib.redirect_stdout(rendered):
                self.assertEqual(run_all_checks.main(), 0)
        finally:
            run_all_checks.CHECKS = original
        text = rendered.getvalue()
        self.assertIn("Scientific result: not evaluated by this process runner", text)
        self.assertNotIn("Declared scope", text)

    def test_remaining_eos_interpolators_fail_closed(self):
        baseline = css.build_baseline_arrays()
        hybrid = css.build_css_hybrid_eos(baseline, 1.8, 0.6, 1.0 / 3.0)
        self.assertIsNotNone(hybrid)
        eps_of_p = css.pressure_to_energy_interpolator(hybrid["p_sorted"], hybrid["e_sorted"])
        with self.assertRaises(ValueError):
            eps_of_p(float(hybrid["p_sorted"][-1]) + 1.0)

        eps, pressure = hyperon.get_nl3_eos("nucleon")
        with self.assertRaises(ValueError):
            hyperon.solve_tov(eps, pressure, pressure[-1] + 1.0)

        interp = interp1d([1.0, 2.0], [10.0, 20.0], bounds_error=True)
        with self.assertRaises(ValueError):
            direct_urca.solve_tov(interp, 3.0)

        for eos in (magnetar.UnifiedEOS(), full_ns.UnifiedEOS(2.0, 0.0)):
            self.assertGreater(eos.get_eps(eos.p_arr[-1]), 0.0)
            with self.assertRaises(ValueError):
                eos.get_eps(eos.p_arr[-1] + 1.0)
            with self.assertRaises(ValueError):
                eos.get_eps(-1.0)

    def test_tracked_outputs_carry_current_status_provenance(self):
        dark = Path(HERE) / "nvg_dark_photon_observables_output.txt"
        magnetar_output = Path(HERE) / "nvg_magnetar_mass_correlation_output.txt"
        dark_text = dark.read_text(encoding="utf-8")
        magnetar_text = magnetar_output.read_text(encoding="utf-8")
        self.assertIn("CONDITIONAL DARK-PHOTON OBSERVABLE SCANS", dark_text)
        self.assertIn("Generated by: verification/nvg_dark_photon_observables.py", dark_text)
        self.assertIn("do not establish a mass-drop bound", dark_text)
        self.assertNotIn("QUANTITATIVE CONFIRMATION", dark_text)
        self.assertIn("Catalog source:", magnetar_text)
        self.assertIn("Generated by: verification/nvg_magnetar_mass_correlation.py", magnetar_text)
        self.assertIn("Evidence status: descriptive model output", magnetar_text)
        self.assertIn("Post-hoc mass-anchor analyses: excluded", magnetar_text)
        self.assertNotIn("with 3 independent mass anchors", magnetar_text)


if __name__ == "__main__":
    unittest.main()
